spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cache
spring.cache.type=caffeine

# Encryption Configuration
encryption.key=${ENCRYPTION_KEY}
encryption.salt=${ENCRYPTION_SALT}
encryption.algorithm=${ENCRYPTION_ALGORITHM}
encryption.gcm.tag.length=${ENCRYPTION_GCM_TAG_LENGTH}
encryption.gcm.iv.length=${ENCRYPTION_GCM_IV_LENGTH}
